# Generated by Django 3.2.7 on 2021-11-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(default='username  ', max_length=150)),
                ('password', models.CharField(default='password ', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
