# Generated by Django 3.2.4 on 2021-08-11 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('fname', models.CharField(default='first name  ', max_length=50)),
                ('lname', models.CharField(default='last name ', max_length=50)),
                ('email', models.EmailField(default='example@gmail.com ', max_length=1000)),
                ('phone', models.CharField(default='90334587654', max_length=1000)),
                ('address', models.CharField(default='no 11 resfgt r ', max_length=100)),
                ('state', models.CharField(default='Lagos ', max_length=50)),
                ('city', models.CharField(default='lekki ', max_length=50)),
                ('zip', models.CharField(default='123456 ', max_length=50)),
                ('account_number', models.IntegerField(default=1234567890)),
                ('bvn', models.IntegerField(default=2345678765)),
                ('bank_name', models.CharField(default='my bsnk nsmr ', max_length=50)),
                ('card_name', models.CharField(default='card name', max_length=100)),
                ('card_number', models.IntegerField(default=456789999, max_length=40)),
                ('card_year', models.DateTimeField(blank=True, default=datetime.date(2021, 8, 11), null=True)),
                ('card_month', models.DateTimeField(default=datetime.date(2021, 8, 11))),
                ('card_cvc', models.IntegerField(default=0, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
